#! /bin/bash

dir=$1
title=$2

current_date=$(date +%Y%m%d)
template_file=$(echo $dir/_template*)

new_file=$dir/$current_date
if [[ -n $title ]]; then
  new_file+=-$title
fi
new_file+=".${template_file##*.}"

sed "s/{{DATE}}/$(date +%Y%m%d)/" $template_file > $new_file
vim $new_file
