* Analysis 1 by Terence Tao

Started reading on 2026-06-14.

- 2026-07-04
  - § 3.1: Read the remainder of the section and did Exercises 3.1.1, 3.1.2,
    3.1.11. Bringing them here is becoming more and more tedious... Today I only
    copied 3.1.1. Maybe I should build an automation tool.
- 2026-07-03
  - § 3.1: I didn't do much today because of the school schedule. Just re-read
    until p. 43 and tried deep understanding of axiom schema of replacement.
- 2026-07-02
  - § 3.1: Re-read yesterday's and made a little more progress up to p. 43.
    Today I focused on the equality axioms in Appendix A, revisiting the rules
    for the equality relation illustrated in Suppes.
  - The treatment of logic in this book is confusing me. I know this is a math
    book, not a strict logic book, but my brain cannot yet handle a "less
    structured" style of axioms and definitions. For example: I don't think the
    constant symbol \(\varnothing\) is introduced with a proper definition; the
    book states an empty set exists (Axiom 3.2), but an explicit definition of
    the \(\varnothing\) symbol is not given.
- 2026-07-01
  - § 3.1: Read pp. 33-39. Also tried to formulate the axioms and definitions
    introduced so far with first-order logic, but I was faced with so many
    holes in my current knowledge with FOL. I'm not sure whether I'm doing this
    "the right way".
- 2026-06-29
  - § 2.3: Did Exercise 2.3.4.
- 2026-06-28
  - § 2.3: Reviewed Definition 2.3.11 (Exponentiation for natural numbers).
- 2026-06-27
  - § 2.3: Did Exercise 2.3.5.
- 2026-06-26
  - § 2.3: Proved Proposition 2.3.6 and Corollary 2.3.7.
- 2026-06-24
  - § 2.3: Proved 2.3.4.
- 2026-06-22
  - § 2.3: Proved 2.3.3.
- 2026-06-21
  - § 2.2: Completed Exercise 2.2.6. Sketched out all proofs for Section 2.3, and
    I'm planning to write them up next week.
- 2026-06-20
  - § 2.2: Did Exercise 2.2.5. Looking up the hint immediately led to a
    solution (although I wanted to prove it by myself...).
- 2026-06-19
  - § 2.2: Worked on Exercise 2.2.5, continuing from yesterday.
- 2026-06-17
  - § 2.2: Did Exercises 2.2.3 and 2.2.4. I have to revisit 2.2.4 tomorrow. I
    didn't solve many problems today, as I spent some time practicing
    mathematical prose and English instead.
- 2026-06-16
  - § 2.2: Read pp. 26-27.
- 2026-06-15
  - § 2.2: Read pp. 24-26. Tried to prove all the propositions/theorems by
    myself before reading them.
- 2026-06-14
  - § 2.1: Read the whole section. Focused on the construction of the Peano
    axioms. Encountered the recursion theorem and sketched out the proof idea.

** My solutions for exercises

I'm practicing proof writing as well as problem solving here, so the writing
style can vary from one solution to another.

*** Exercise 2.2.3

**** (a) \(a \ge a\).

Proof. We seek an m such that \(a = a + m\). Clearly 0 is such an \(m\), and
hence \(a \ge a\).

**** (b) If \(a \ge b\) and \(b \ge c\), then \(a \ge c\).

Proof. Let \(m\) and \(n\) be natural numbers such that \(a = b + m\) and \(b =
c + n\).
Then we have \(a = (c + n) + m\).
By the associative law for addition, \(a = c + (n + m)\).
Therefore \(a \ge c\).

**** (c) If \(a \ge b\) and \(b \ge a\), then \(a = b\).

Proof. Let \(m\) and \(n\) be natural numbers such that \(a = b + m\) and \(b =
a + n\).
Then we have \(a = (a + n) + m\) and \(a = a + (n + m)\), and so \(n +
m\) must be zero.
Thus \(n = m = 0\) by Corollary 2.2.9. Substituting \(0\) for \(m\) into \(a =
b + m\), we conclude that \(a = b\).

***** Lemma. If \(a + m = a\) then \(m = 0\).

Proof. \(a + m = a = a + 0\). Using the cancellation law gives \(m = 0\).

**** (d) \(a \ge b\) iff \(a + c \ge b + c\).

Proof.

***** (i) If \(a \ge b\) then \(a + c \ge b + c\).

Let \(a = b + m\) for some natural number \(m\). Then \(a + c = (b + c) + m\),
hence \(a + c \ge b + c\).

***** (ii) If \(a + c \ge b + c\) then \(a \ge b\).

Since \(a + c \ge b + c\), there exists a natural number m such that \(a + c =
(b + c) + m\).
Then \(a + c = (b + m) + c\). By the cancellation law \(a = b +
m\). Hence \(a \ge b\).

**** (e) \(a < b\) iff \(a \textt{++} \le b\).

Proof. First, suppose \(a < b\). Then there exists a natural number \(m\) such
that

\[b = a + m\]

Since \(a < b\) implies \(a \ne b\), \(m \ne 0\). Thus by Lemma 2.2.10, there is
a natural number \(n\) such that \(n \textt{++} = m\). Hence

\[
b = a + (n \textt{++}) = (a + n)\textt{++} = (a \textt{++}) + n
\]

Therefore \(a \textt{++} \le b\).

Conversely, suppose that \(a \textt{++} \le b\). Let \(m\) be a natural number
such that \(b = (a \textt{++}) + m\). Then

\[
b = (a \textt{++}) + m = (a + m)\textt{++} = a + (m \textt{++})
\]

Suppose, for contradiction, that \(a = b\). Then

\[
a = a + (m \textt{++})
\]

and cancelling a gives \(m \textt{++} = 0\). But that contradicts Axiom 2.3,
which says \(m \textt{++} \ne 0\). Thus \(a \ne b\).

Since \(b = a + (m \textt{++})\), we conclude that \(a < b\).

**** (f) \(a < b\) iff \(b = a + d\) for some positive number \(d\).

Proof. First, assume that \(a < b\). Then \(b = a + d\) for some natural
number \(d\). Suppose, for contradiction, that \(d = 0\). then \(b = a + 0 = a\),
contradicting the fact that \(a \ne b\). Hence \(d \ne 0\), and we conclude
\(d\) is positive.

Conversely, assume that \(b = a + d\) for some positive number \(d\).
If \(a =
b\), \(d = 0\) by the same argument used in (e),
contradicting the fact that \(d
\ne 0\). Thus \(a \ne b\) and we conclude that \(a < b\).

*** Exercise 2.2.4

Proposition 2.2.13. Let \(a\) and \(b\) be natural numbers. Then exactly one of
the following statements is true: \(a < b\), \(a = b\), \(a > b\).

Proof. We first prove that at most one of the statements is true. If \(a = b\),
by definition \(a < b\) and \(a > b\) is false. If \(a < b\) or \(a > b\), then
by definition \(a \ne b\). Finally, if \(a < b\) and \(a > b\), then \(a = b\)
by Proposition 2.2.12.(c), a contradiction. Hence at most one of the statements
is true.

We now prove that at least one of the statements is true. We proceed by
induction on \(a\). Consider the base case \(a = 0\). Since \(b = 0 + b\), we
have \(0 \le b\) for all \(b\). Thus either \(0 < b\) or \(0 = b\), and the base
case is done. Now suppose inductively that \(a < b \lor a = b \lor a > b\). We
need to show that the proposition still holds on \(a \textt{++}\). If \(a = b\), we have
\(a \textt{++} = b \textt{++} = b + 1\). Since \(a \textt{++} \ne b\), \(a
\textt{++} > b\). If \(a < b\), \(a \textt{++} \le b\) by Proposition
2.2.12.(e). Then either \(a \textt{++} < b\) or \(a \textt{++} = b\), and in
either case we are done. Finally, if \(a > b\) then for some natural number
\(m\), \(a = b + m\). Now \(a \textt{++} = (b + m) \textt{++} = b + (m
\textt{++})\). Hence \(a \textt{++} > b\).
This closes the induction.

*** Exercise 2.2.5.

Proposition 2.2.14 (Strong principle of induction). Let $m_0$ be a natural number,
and let $P(m)$ be a property pertaining to an arbitrary natural number $m$.
Suppose that for each $m \geq m_0$, we have the following implication:
If $P(m')$ is true for all natural numbers $m_0 \leq m' < m$, then $P(m)$ is also true.
(In particular, this means that $P(m_0)$ is true, since in this case the hypothesis is vacuous.)
Then $P(m)$ is true for all natural numbers $m \geq m_0$.

The solution became unnecessarily long here because I tried to give a different
proof for each lemma.

**** Lemma a. \(a \ne 0 \to \exists m(N(m) \land a = 1 + m)\).

Proof. Since \(a\) is positive, by Lemma 2.2.10 there exists a natural number
\(m\) such that \(a = m\textt{++}\). Then we have
\(a = m\textt{++} = 0 +
m\textt{++} = (0 + m)\textt{++} = (0\textt{++}) + m = 1 + m\).

**** Lemma b. \(m \ne 0 \land n \ne 0 \to m + n \ne 1\).

Proof 1. Suppose \(m + n = 1\). by Lemma 2.2.10, there exist natural numbers
\(p\) and \(q\) such that \(p\textt{++} = m\) and \(q\textt{++} = n\). then
\(m + n = (p\textt{++}) + (q\textt{++}) = ((p + q)\textt{++})\textt{++} = 1 =
0\textt{++}\). by Axiom 2.4. we infer \((p + q)\textt{++} = 0\), contradicting
axiom 2.3., i.e., \((p + q) \ne 0\). hence \(m + n \ne 1\).

Proof 2. Suppose \(m + n = 1\). by Lemma 2.2.10, there exists a natural number
\(p\) such that \(p\textt{++} = m\). then \(m + n = (p\textt{++}) + n = (p +
n)\textt{++} = 1 = 0\textt{++}\).
by axiom 2.4 we infer \(p + n = 0\). but since \(n\) is positive, \(p + n \ne
0\) By Proposition 2.2.8,
a contradiction. Hence \(m + n \ne 1\).

**** Lemma c. \(a < b\textt{++} \land a \ne b \to a < b\).

Proof 1 (direct). By Proposition 2.2.12.(f), \(b\textt{++} = a + n\) for some
positive number \(n\). Since \(n\) is positive, by Lemma a there exists an \(m\)
such that \(n = m + 1\). Now \(b \textt{++} = b + 1 = a + n = a + (m + 1) =
(a + m) + 1\).
Cancelling 1 from both sides yields \(b = a + m\). Thus \(b \ge a\).
Since we also have \(a \ne b\), we conclude that \(b > a\).

Proof 2 (indirect). Suppose \(a < b\) is false. Then by Proposition 2.2.13, \(a
> b\) must hold.
Now choose two positive numbers \(n\) and \(m\) such that \(b\textt{++} = a +
n\) and \(a = b + m\).
Now \(b\textt{++} = b + 1 = a + n =
(b + m) + n = b + (m + n)\).
Cancelling \(b\) from both sides gives \(m + n =
1\). But this contradicts Lemma b, since \(m\) and \(n\) are both positive.
Hence \(b > a\).

**** Proof

Proof. Let \(Q(n)\) be the property that \(P(m)\) is true for all \(m_0 \le m <
n\).
We prove by induction that \(Q(n)\) is true for every natural number \(n\).

If \(n = 0\) then \(Q(0)\) is vacuously true, since there's no \(m\) such that \(m <
0\).

Now suppose inductively that \(Q(n)\). Let \(m\) satisfy \(m_0 \le m < n\textt{++}\).
We must show \(P(m)\). We can think of two cases here: \(m = n\)
and \(m \ne n\).

First, consider the case \(m = n\). Notice that by the inductive hypothesis,
\(P(m^{\prime})\) for all \(m_0 \le m^{\prime} < n\). It follows that \(P(n)\), i.e., \(P(m)\),
from the hypothesis of the theorem, and we are done.

Now if \(m \ne n\), by Lemma c \(m < n\). Thus by the inductive hypothesis we
infer that \(P(m)\).

This closes the induction, and we have proven that \(Q(n)\) holds for every
natural number \(n\).

Using this result, we now show the conclusion of the theorem, that is, \(P(m)\)
for all \(m \ge m_0\). For every natural number \(m \ge m_0\),
\(Q(m\textt{++})\) holds, since \(m\textt{++}\) is a natural number.
Together with the fact that \(m_0 \le m < m\textt{++}\), we conclude that
\(P(m)\). This demonstrates the strong principle of induction.

*** Exercise 2.2.6.

Let $n$ be a natural number, and let $P(m)$ be a property pertaining to the
natural numbers such that whenever $P(m++)$ is true, then $P(m)$ is true.
Suppose that $P(n)$ is also true. Prove that $P(m)$ is true for all natural
numbers $m \leq n$; this is known as the principle of backwards induction.

**** Initial solution

***** Lemma. If \(m \le 0\) then \(m = 0\).

Proof. Let \(m \le 0\). By definition \(0 = m + n\) for some natural number
\(n\). But by Corollary 2.2.9, \(m\) and \(n\) must both be zero. Hence \(m = 0\).

***** Solution

We induct on \(n\). We first prove the principle holds on \(n = 0\). Let m be a
natural number such that \(m \le 0\). Then \(m\) must be \(0\), and from \(P(0)\) we
immediately obtain that \(P(m)\).

Now suppose inductively that the principle holds on \(n\). We have to prove the
principle on \(n\textt{++}\). We first obtain the conclusion of the inductive
hypothesis. We have \(P(n\textt{++})\), so we infer \(P(n)\) from the
hypothesis. we have the requirements of backwards induction on n, and thus
\(P(m)\) is true for every natural number \(m \le n\).

Now let \(m\) be a natural number such that \(m \le n\textt{++}\). If \(m =
n\textt{++}\),
then \(P(n\textt{++})\), i.e., \(P(m)\) and we are done.
Otherwise, \(m \le n\) and from the earlier result we obtain \(P(m)\). This
closes the induction, and we have demonstrated the principle of backwards
induction.

**** Solution with revised writing & structure

Using the same lemma as above.

Let \(Q(n)\) be the property that: "if \(P(n)\) is true, then \(P(m)\) is true for
all \(m \le n\)". We prove \(Q(n)\) for every natural number \(n\), using induction.

Consider the base case \(n = 0\). Let \(m \le 0\). Then \(m\) must be \(0\) by
the above lemma, and since \(P(0)\), we conclude that \(P(m)\).

Suppose inductively that \(Q(n)\). We have to prove \(Q(n\textt{++})\). From
\(P(n\textt{++})\) and the definition of \(P\), we have \(P(n)\). Thus by the
inductive hypothesis, \(P(m)\) for all \(m \le n\).

Now let \(m\) be a natural number such that \(m \le n\textt{++}\). If \(m =
n\textt{++}\),
then we subtitute \(m\) for \(n\textt{++}\) in \(P(n\textt{++})\), and we are done.
Otherwise, \(m \le n\) and thus \(P(m)\). This closes the induction.

*** The product of two natural numbers is a natural number.

Proof. Let \(n\), \(m\) be natural numbers. We induct on \(n\), keeping \(m\)
fixed.

The base case is obvious, since \(0 \cdot m = 0\), and \(0\) is a natural
number.

Now suppose inductively that \(n \cdot m\) is a natural number. Then
\((n\textt{++}) \cdot m = (n \cdot m) + n\) by Definition 2.3.1.
Since \(n \cdot
m\) and \(m\) are natural numbers, \((n \cdot m) + n\) is so by the property of
addition. This closes the induction.

*** Exercise 2.3.1.

Lemma 2.3.2 (Multiplication is commutative). Let \(n\), \(m\) be natural
numbers. Then \(n \cdot m = m \cdot n\).

**** Lemma. \(n \cdot 0 = 0\).

Proof. We prove by induction. The base case \(0 \cdot 0 = 0\) is straightforward
from the definition. Now if \(n \cdot 0 = 0\), then \((n\textt{++}) \cdot 0 = (n
\cdot 0) + 0 = 0 + 0 = 0\).

**** Lemma. \(m \cdot (n\textt{++}) = (m \cdot n) + m\).

Proof. We use induction on \(m\). For the base case, by definition of multiplication we
have \(0 \cdot (n\textt{++}) = 0 = 0 + 0 = (0 \cdot n) + 0\), and we are
done.

Now suppose inductively that \(m \cdot (n \textt{++}) = (m \cdot n) + m\). Then
by definition of multiplication

\[
(m\textt{++}) \cdot (n\textt{++}) = (m \cdot (n\textt{++})) + n\textt{++}
= (m \cdot n + m) + n\textt{++}
\]

And the properties of addition gives

\[
(m \cdot n + m) + n\textt{++}
= m \cdot n + (m + n) \textt{++}
= m \cdot n + n + (m\textt{++})
\]

Finally, applying the definition of multiplication we obtain

\((m\textt{++}) \cdot n + m\textt{++}\).

Thus \((m \textt{++}) \cdot (n\textt{++}) = (m\textt{++}) \cdot n + m\textt{++}\).
This closes the induction.

**** Solution

We induct on \(n\). Consider the base case \(n = 0\). Then by definition of
multiplication and the first lemma, \(0 \cdot m = 0 = m \cdot 0\).

Now we prove the inductive step \((n \textt{++}) \cdot m = m \cdot
(n\textt{++})\).
We start from the inductive hypothesis \(n \cdot m = m \cdot
n\).
We add \(m\) to both sides and obtain \((n \cdot m) + m = (m \cdot n) +
m\).
By definition, LHS is equal to \((n\textt{++}) \cdot m\). Also, the above
lemma says that \((m \cdot n) + m\) is equal to \(m \cdot (n\textt{++})\). Thus
we conclude that \((n\textt{++}) \cdot m = m \cdot (n\textt{++})\), and this
closes the induction.

*** Exercise 2.3.2

Lemma 2.3.3 (Positive natural numbers have no zero divisors). Let \(n\), \(m\)
be natural numbers. Then \(n \cdot m = 0\) if and only if at least one of \(n\),
\(m\) is equal to zero. In particular, if \(n\) and \(m\) are both positive,
then \(nm\) is also positive.

Proof. First, suppose that \(n = 0 \lor m = 0\). If \(n = 0\), then by
Definition 2.3.1 \(n \cdot m = 0 \cdot m = 0\). Otherwise, \(m = 0\), and
\(m \cdot n = 0\) by the same argument. Since multiplication is commutative,
that leads to \(n \cdot m = 0\).

Conversely, suppose that \(nm = 0\), and for contradiction both \(n\) and \(m\)
are positive. Then by Lemma 2.2.10, \(n = p\textt{++}\) for some natural \(p\).
Now \(n \cdot m = (p\textt{++}) \cdot m\), and by definition of multiplication
\(n \cdot m = p \cdot m + m\). Since \(n \cdot m = 0\), we have \(p \cdot m + m = 0\).
By Corollary 2.2.9 it follows that \(m = 0\), a contradiction.
Thus at least one of \(n\) and \(m\) must be zero.

*** Proposition 2.3.4

Proposition 2.3.4 (Distributive Law). For any natural numbers \(a\), \(b\),
\(c\), we have \(a(b + c) = ab + ac\) and \((b + c)a = ba + ca\).

Proof. Since multiplication is commutative, we only have to show the first
identity. We induct on \(a\), keeping \(b\) and \(c\) fixed.

For the base case \(a = 0\), we have the following identities:

\(0(b + c) = 0 = 0 + 0 = 0b + 0c\)

Hence the base case is done.

Now suppose inductively that \(a(b + c) = ab + ac\). Then

\begin{equation*}
\begin{align*}
(a\textt{++})(b + c) & = a(b + c) + b + c & \text{Definition of multiplication} \\
& = (ab + ac) + b + c & \text{Inductive hypothesis} \\
& = (ab + b) + (ac + c) & \text{Commutativity and associativity of addition} \\
& = (a\textt{++})b + (a\textt{++})c & \text{Definition of multiplication}
\end{align*}
\end{equation*}

This proves the inductive step, and thus \(a(b + c) = ab + ac\) for all natural
numbers \(a\), \(b\), \(c\).

*** Exercise 2.3.3

Proposition 2.3.5 (Multiplication is associative). For any natural numbers
\(a\), \(b\), \(c\), we have \((a \cdot b) \cdot c = a \cdot (b \cdot c)\).

Proof. We use induction on \(a\). The base case \(a = 0\) is straightforward:
both \((0 \cdot b) \cdot c\) and \(0 \cdot (b \cdot c)\) are equal to \(0\) by the definition of multiplication.

Now suppose inductively that \((a \cdot b) \cdot c = a \cdot (b \cdot c)\).
We need to show that \(((a\textt{++}) \cdot b) \cdot c = (a\textt{++}) \cdot (b \cdot c)\).
The left-hand side is \((a \cdot b + b) \cdot c\) by definition, which is by distributive law
equal to \((a \cdot b) \cdot c + b \cdot c\). The right-hand side is
\(a \cdot (b \cdot c) + b \cdot c\). But by the inductive hypothesis \((a \cdot b) \cdot c = a \cdot (b \cdot c)\),
so we conclude that both sides are equal. This closes the induction.

*** Proposition 2.3.6

Proposition 2.3.6 (Multiplication preserves order). If \(a\), \(b\) are natural
numbers such that \(a < b\), and \(c\) is positive, then \(ac < bc\).

Proof. By Proposition 2.2.12.(f), there exists a positive number \(m\) such that
\(b = a + m\). Then \(bc = (a + m)c = ac + mc\). Since \(m\) and \(c\) are both
positive, \(mc > 0\) by Lemma 2.3.3. Thus, using Proposition 2.2.12.(f) again,
we can conclude that \(bc > ac\).

*** Corollary 2.3.7

Corollary 2.3.7 (Cancellation law). Let \(a\), \(b\), \(c\) be natural numbers
such that \(ac = bc\) and \(c\) is non-zero. Then \(a = b\).

Proof. We proceed by contradiction. Suppose \(a \ne b\). Then by the trichatomy
of order, either \(a > b\) or \(a < b\). If \(a > b\), by Proposition 2.3.6 \(ac
> bc\),
which contradicts \(ac = bc\). We can also obtain the same result when
\(a < b\). Hence \(a = b\).

*** Exercise 2.3.4

Prove the identity \((a + b)^2 = a^2 + 2ab + b^2\) for all natural numbers
\(a\), \(b\).

Lemma. \(a^1 = a\) for all natural number \(a\).

Proof. \(a^1 = a^{0\textt{++}} = a^0 \cdot a = 1 \cdot a = a\).

We now prove the identity \((a + b)^2 = a^2 + 2ab + b^2\) by the following identities:

\begin{equation*}
\begin{align*}
(a + b)^2 & = (a + b)^1 \cdot (a + b) & \text{Definition of exponentiation} \\
& = (a + b) \cdot (a + b) & \text{Lemma} \\
& = (a + b) \cdot a + (a + b) \cdot b & \text{Distributive law} \\
& = aa + ba + ab + bb & \text{Distributive law again} \\
& = aa + ab + ab + bb & \text{Commutativity of multiplication} \\
& = aa + 1ab + ab + bb & \text{Identity of multiplication} \\
& = aa + 2ab + bb & \text{Definition of multiplication} \\
& = a^1a + 2ab + b^1b & \text{Lemma} \\
& = a^2 + 2ab + b^2 & \text{Definition of exponentiation}
\end{align*}
\end{equation*}
.

(Since the exercise comes immediately after the definition of exponentiation, I
decided to be verbose here.)

*** Exercise 2.3.5

Proposition 2.3.9 (Euclidean algorithm). Let \(n\) be a natural number, and let
\(q\) be a positive number. Then there exist natural numbers \(m\), \(r\) such
that \(0 \le r < q\) and \(n = mq + r\).

Proof. We induct on \(n\), keeping \(q\) fixed. Consider the base case \(n =
0\).
Then we can choose \(m = 0\) and \(r = 0\), since \(0 < q\) and \(0 = 0q + 0\).

Now suppose inductively that there exist natural numbers \(m\) and \(r\)
satisfying the conditions. We have to find \(m^{\prime}\) and \(r^{\prime}\)
such that \(0 \le r^{\prime} < q\) and \(n\textt{++} = m^{\prime}q + r^{\prime}\).

Since \(n = mq + r\), we have \(n\textt{++} = (m^{\prime}q + r)\textt{++} = m^{\prime} + (r\textt{++})\).

By the inductive hypothesis \(r < q\), and thus \(r\textt{++} \le q\). So we have
two cases here: \(r\textt{++} < q\) or \(r\textt{++} = q\).

If \(r\textt{++} <
q\), then \(m^{\prime} = m\) and \(r^{\prime} = r\textt{++}\), so we are done.
Otherwise \(r\textt{++} = q\), and then \(mq + (r\textt{++}) = mq + q = (m + 1)q\).
Hence we can choose \(m^{\prime} = m + 1\) and \(r = 0\). This closes the induction.

*** Exercise 3.1.1.

Show that the definition of equality in Definition 3.1.4 is reflexive,
symmetric, and transitive.

Proof. Let \(A\), \(B\), \(C\) be sets. First, for any object \(x\) we have \(x \in A \leftrightarrow x
\in A\),
since it's a tautology. Hence \(A = A\). If \(A = B\) then for any object \(x\), \(x \in A \leftrightarrow x \in B\) .
But that is equivalent to \(x \in B \leftrightarrow x \in A\), which leads to \(B = A\). Finally, suppose
that \(A = B\) and \(B = C\). Then for any object \(x\), \(x \in A \leftrightarrow x \in B\)
and \(x \in B \leftrightarrow x \in C\). Thus we have \(x \in A \leftrightarrow x \in C\),
which is equivalent to \(A = C\).

*** Exercise 3.1.11.

Show that the axiom of replacement implies the axiom of specification.

Proof. Let \(A\) be a set, and let \(P(x)\) be a property pertaining to the elements of \(A\).
We have to show that there exists a set \(X\) such that for any object \(x\),
\(x \in X\) if and only if \(x \in A\) and \(P(x)\).

Let \(Q(x, y)\) be the statement "\(x = y\) and \(P(x)\)".

We claim that for each \(x \in A\), there is at most one \(y\) for which \(Q(x, y)\) is true.
Let \(x \in A\), and let \(y_1\), \(y_2\) satisfy \(Q(x, y_1)\) and \(Q(x, y_2)\). Then \(x = y_1\) and \(x = y_2\),
which then implies \(y_1 = y_2\). Hence our claim is true, and by Axiom of replacement there exists a set \(Y\)
such that for any object \(z\), \(z \in Y\) if and only if \(Q(x, z)\) for some \(x \in A\).

We now prove that \(Y\) is the \(X\) we are seeking, i.e.,
for every \(z\), \(z \in Y\) if and only if \(z \in A\) and \(P(z)\).

First, suppose \(z \in A\) and \(P(z)\). To show that \(z \in Y\),
we have to find an \(x \in A\) such that \(Q(x, z)\) holds. Indeed, \(Q(z, z)\) holds,
since \(z = z\) and \(P(z)\). Thus, \(z\) is such an \(x\), and therefore \(z \in Y\).

Conversely, let \(z \in Y\). Then there exists an \(x \in A\) such that \(Q(x, z)\),
i.e., \(x = z\) and \(P(x)\). Since \(x = z\), it follows that \(P(z)\) and \(z \in A\).

Hence, \(Y\) is the set we were looking for, and this completes our proof.
