* Analysis 1 by Terence Tao

Started reading on 2026-06-14.

- 2026-06-20
  - § 2.2: Did Exercise 2.2.4. Looking up the hint immediately led to a
    solution (although I wanted to prove it by myself...).
- 2026-06-19
  - § 2.2: Worked on Exercise 2.2.4, continuing from yesterday.
- 2026-06-17
  - § 2.2: Did Exercises 2.2.3 and 2.2.4. I have to revisit 2.2.4 tomorrow. I
    didn't solve many problems today, as I spent some time practicing
    mathematical prose and English instead.
- 2026-06-16
  - § 2.2: Read pp. 26-27.
- 2026-06-15
  - § 2.2: Read pp. 24-26. Tried to prove all the propositions/theorems by
    myself before reading them.
- 2026-06-14
  - § 2.1: Read the whole section. Focused on the construction of the Peano
    axioms. Encountered the recursion theorem and sketched out the proof idea.

** My solutions for exercises

I'm practicing proof writing as well as problem solving here, so the writing
style can vary from one solution to another.

*** Exercise 2.2.3

**** (a) \(a \ge a\).

Proof. We seek an m such that \(a = a + m\). Clearly 0 is such an \(m\), and
hence \(a \ge a\).

**** (b) If \(a \ge b\) and \(b \ge c\), then \(a \ge c\).

Proof. Let \(m\) and \(n\) be natural numbers such that \(a = b + m\) and \(b =
c + n\).
Then we have \(a = (c + n) + m\).
By the associative law for addition, \(a = c + (n + m)\).
Therefore \(a \ge c\).

**** (c) If \(a \ge b\) and \(b \ge a\), then \(a = b\).

Proof. Let \(m\) and \(n\) be natural numbers such that \(a = b + m\) and \(b =
a + n\).
Then we have \(a = (a + n) + m\) and \(a = a + (n + m)\), and so \(n +
m\) must be zero.
Thus \(n = m = 0\) by Corollary 2.2.9. Substituting \(0\) for \(m\) into \(a =
b + m\), we conclude that \(a = b\).

***** Lemma. If \(a + m = a\) then \(m = 0\).

Proof. \(a + m = a = a + 0\). Using the cancellation law gives \(m = 0\).

**** (d) \(a \ge b\) iff \(a + c \ge b + c\).

Proof.

***** (i) If \(a \ge b\) then \(a + c \ge b + c\).

Let \(a = b + m\) for some natural number \(m\). Then \(a + c = (b + c) + m\),
hence \(a + c \ge b + c\).

***** (ii) If \(a + c \ge b + c\) then \(a \ge b\).

Since \(a + c \ge b + c\), there exists a natural number m such that \(a + c =
(b + c) + m\).
Then \(a + c = (b + m) + c\). By the cancellation law \(a = b +
m\). Hence \(a \ge b\).

**** (e) \(a < b\) iff \(a \textt{++} \le b\).

Proof. First, suppose \(a < b\). Then there exists a natural number \(m\) such
that

\[b = a + m\]

Since \(a < b\) implies \(a \ne b\), \(m \ne 0\). Thus by Lemma 2.2.10, there is
a natural number \(n\) such that \(n \textt{++} = m\). Hence

\[
b = a + (n \textt{++}) = (a + n)\textt{++} = (a \textt{++}) + n
\]

Therefore \(a \textt{++} \le b\).

Conversely, suppose that \(a \textt{++} \le b\). Let \(m\) be a natural number
such that \(b = (a \textt{++}) + m\). Then

\[
b = (a \textt{++}) + m = (a + m)\textt{++} = a + (m \textt{++})
\]

Suppose, for contradiction, that \(a = b\). Then

\[
a = a + (m \textt{++})
\]

and cancelling a gives \(m \textt{++} = 0\). But that contradicts Axiom 2.3,
which says \(m \textt{++} \ne 0\). Thus \(a \ne b\).

Since \(b = a + (m \textt{++})\), we conclude that \(a < b\).

**** (f) \(a < b\) iff \(b = a + d\) for some positive number \(d\).

Proof. First, assume that \(a < b\). Then \(b = a + d\) for some natural
number \(d\). Suppose, for contradiction, that \(d = 0\). then \(b = a + 0 = a\),
contradicting the fact that \(a \ne b\). Hence \(d \ne 0\), and we conclude
\(d\) is positive.

Conversely, assume that \(b = a + d\) for some positive number \(d\).
If \(a =
b\), \(d = 0\) by the same argument used in (e),
contradicting the fact that \(d
\ne 0\). Thus \(a \ne b\) and we conclude that \(a < b\).

*** Exercise 2.2.4

Proposition 2.2.13. Let \(a\) and \(b\) be natural numbers. Then exactly one of
the following statements is true: \(a < b\), \(a = b\), \(a > b\).

Proof. We first prove that at most one of the statements is true. If \(a = b\),
by definition \(a < b\) and \(a > b\) is false. If \(a < b\) or \(a > b\), then
by definition \(a \ne b\). Finally, if \(a < b\) and \(a > b\), then \(a = b\)
by Proposition 2.2.12.(c), a contradiction. Hence at most one of the statements
is true.

We now prove that at least one of the statements is true. We proceed by
induction on \(a\). Consider the base case \(a = 0\). Since \(b = 0 + b\), we
have \(0 \le b\) for all \(b\). Thus either \(0 < b\) or \(0 = b\), and the base
case is done. Now suppose inductively that \(a < b \lor a = b \lor a > b\). We
need to show that the proposition still holds on \(a \textt{++}\). If \(a = b\), we have
\(a \textt{++} = b \textt{++} = b + 1\). Since \(a \textt{++} \ne b\), \(a
\textt{++} > b\). If \(a < b\), \(a \textt{++} \le b\) by Proposition
2.2.12.(e). Then either \(a \textt{++} < b\) or \(a \textt{++} = b\), and in
either case we are done. Finally, if \(a > b\) then for some natural number
\(m\), \(a = b + m\). Now \(a \textt{++} = (b + m) \textt{++} = b + (m
\textt{++})\). Hence \(a \textt{++} > b\).
This closes the induction.

*** Exercise 2.2.5.

Proposition 2.2.14 (Strong principle of induction). Let $m_0$ be a natural number,
and let $P(m)$ be a property pertaining to an arbitrary natural number $m$.
Suppose that for each $m \geq m_0$, we have the following implication:
If $P(m')$ is true for all natural numbers $m_0 \leq m' < m$, then $P(m)$ is also true.
(In particular, this means that $P(m_0)$ is true, since in this case the hypothesis is vacuous.)
Then $P(m)$ is true for all natural numbers $m \geq m_0$.

The solution became unnecessarily long here because I tried to give a different
proof for each lemma.

**** Lemma a. \(a \ne 0 \to \exists m(N(m) \land a = 1 + m)\).

Proof. Since \(a\) is positive, by Lemma 2.2.10 there exists a natural number
\(m\) such that \(a = m\textt{++}\). Then we have
\(a = m\textt{++} = 0 +
m\textt{++} = (0 + m)\textt{++} = (0\textt{++}) + m = 1 + m\).

**** Lemma b. \(m \ne 0 \land n \ne 0 \to m + n \ne 1\).

Proof 1. Suppose \(m + n = 1\). by Lemma 2.2.10, there exist natural numbers
\(p\) and \(q\) such that \(p\textt{++} = m\) and \(q\textt{++} = n\). then
\(m + n = (p\textt{++}) + (q\textt{++}) = ((p + q)\textt{++})\textt{++} = 1 =
0\textt{++}\). by Axiom 2.4. we infer \((p + q)\textt{++} = 0\), contradicting
axiom 2.3., i.e., \((p + q) \ne 0\). hence \(m + n \ne 1\).

Proof 2. Suppose \(m + n = 1\). by Lemma 2.2.10, there exists a natural number
\(p\) such that \(p\textt{++} = m\). then \(m + n = (p\textt{++}) + n = (p +
n)\textt{++} = 1 = 0\textt{++}\).
by axiom 2.4 we infer \(p + n = 0\). but since \(n\) is positive, \(p + n \ne
0\) By Proposition 2.2.8,
a contradiction. Hence \(m + n \ne 1\).

**** Lemma c. \(a < b\textt{++} \land a \ne b \to a < b\).

Proof 1 (direct). By Proposition 2.2.12.(f), \(b\textt{++} = a + n\) for some
positive number \(n\). Since \(n\) is positive, by Lemma a there exists an \(m\)
such that \(n = m + 1\). Now \(b \textt{++} = b + 1 = a + n = a + (m + 1) =
(a + m) + 1\).
Cancelling 1 from both sides yields \(b = a + m\). Thus \(b \ge a\).
Since we also have \(a \ne b\), we conclude that \(b > a\).

Proof 2 (indirect). Suppose \(a < b\) is false. Then by Proposition 2.2.13, \(a
> b\) must hold.
Now choose two positive numbers \(n\) and \(m\) such that \(b\textt{++} = a +
n\) and \(a = b + m\).
Now \(b\textt{++} = b + 1 = a + n =
(b + m) + n = b + (m + n)\).
Cancelling \(b\) from both sides gives \(m + n =
1\). But this contradicts Lemma b, since \(m\) and \(n\) are both positive.
Hence \(b > a\).

**** Proof

Proof. Let \(Q(n)\) be the property that \(P(m)\) is true for all \(m_0 \le m <
n\).
We prove by induction that \(Q(n)\) is true for every natural number \(n\).

If \(n = 0\) then \(Q(0)\) is vacuously true, since there's no \(m\) such that \(m <
0\).

Now suppose inductively that \(Q(n)\). Let \(m\) satisfy \(m_0 \le m < n\textt{++}\).
We must show \(P(m)\). We can think of two cases here: \(m = n\)
and \(m \ne n\).

First, consider the case \(m = n\). Notice that by the inductive hypothesis,
\(P(m^{\prime})\) for all \(m_0 \le m^{\prime} < n\). It follows that \(P(n)\), i.e., \(P(m)\),
from the hypothesis of the theorem, and we are done.

Now if \(m \ne n\), by Lemma c \(m < n\). Thus by the inductive hypothesis we
infer that \(P(m)\).

This closes the induction, and we have proven that \(Q(n)\) holds for every
natural number \(n\).

Using this result, we now show the conclusion of the theorem, that is, \(P(m)\)
for all \(m \ge m_0\). For every natural number \(m \ge m_0\),
\(Q(m\textt{++})\) holds, since \(m\textt{++}\) is a natural number.
Together with the fact that \(m_0 \le m < m\textt{++}\), we conclude that
\(P(m)\). This demonstrates the strong principle of induction.


